# Generated by Django 3.2.8 on 2021-10-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='author',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='created',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='updated',
        ),
    ]
