# Generated by Django 3.2.8 on 2021-10-15 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20211015_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='fotos',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='block/fotos/'),
            preserve_default=False,
        ),
    ]
