# Generated by Django 3.2.8 on 2021-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_denuncia_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='block/fotos/', verbose_name='Enviar Arquivo'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='message',
            field=models.TextField(verbose_name='Descrição do Caso'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Caso'),
        ),
    ]
