# Generated by Django 3.2.8 on 2021-11-22 16:12

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20211117_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='blockchain',
            field=models.TextField(verbose_name=django.forms.widgets.HiddenInput),
        ),
    ]
