# Generated by Django 3.2.8 on 2021-11-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_alter_denuncia_blockchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='blockchain',
        ),
    ]
